# INSTALL POSTGRESQL
RUN wget https://ftp.postgresql.org/pub/source/v14.0/postgresql-14.0.tar.gz \
    && tar -zxf postgresql-14.0.tar.gz \
    && cd postgresql-14.0 \
    && ./configure --without-readline --without-zlib\
    && make \
    && make install \
    && export PATH="/usr/local/psql:${PATH}"

# USER 'make' and 'psql' to create the dev database
COPY database/postgresql database/psql
# TODO: psql not found error when running psql commands (uncomment below)
# RUN make psql-db-refresh
