/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.ga4gh.drs;

import org.testng.annotations.*;
import org.testng.Assert;

public class AppTest {
    @Test public void helloWorldTest() {
        Assert.assertEquals("helloworld", "helloworld");
    }
}
