/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.ga4gh.starterkit.drs;

import org.testng.Assert;
import org.testng.annotations.Test;

public class AppTest {
    @Test
    public void helloWorldTest() {
        Assert.assertEquals("helloworld", "helloworld");
    }
}
