# this workflow is triggered when a PR to the develop branch is merged.
# the following steps are performed:
#   - build docker image and push to ECR (image tag is the git describe output as well as 'latest')
name: AWS ECR Build and Push
on:
  push:
    branches:
      - develop
      - ja-iss-5-db-schema-and-liquibase # temporary branch for testing, to be removed once workflow is verified
permissions:
  id-token: write
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        id: checkout-code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: save command output
        id: save-command-output
        run: |
          echo "DOCKER_REPO=refcloud-api" >> $GITHUB_ENV
          echo "DOCKER_TAG=$(git describe --tags)" >> $GITHUB_ENV

      - name: configure aws credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build liquibase docker image
        id: build-liquibase-docker-image
        run: docker buildx build --platform linux/amd64,linux/arm64 --load -t ${{ env.DOCKER_REPO }}-liquibase:${{ env.DOCKER_TAG }} -t ${{ env.DOCKER_REPO }}-liquibase:latest -t ${{ env.DOCKER_REPO }}-liquibase:develop liquibase --push

      - name: push predeploy image to ecr
        id: push-liquibase-image-to-ecr
        uses: jwalton/gh-ecr-push@v2
        with:
          region: ${{ secrets.AWS_REGION }}
          local-image: ${{ env.DOCKER_REPO }}-liquibase:${{ env.DOCKER_TAG }}
          image: ${{ env.DOCKER_REPO }}-liquibase:${{ env.DOCKER_TAG }}, ${{ env.DOCKER_REPO }}-liquibase:latest, ${{ env.DOCKER_REPO }}-liquibase:develop